[build.environment]
    NODE_VERSION = "18.12.1"
    NPM_VERSION = "8.19.2" 
    
[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
permissions-policy = "camera=(), microphone=(),geolocation=(), usb=()"